# Generated by Django 5.1.5 on 2025-04-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
