# Generated by Django 5.1.5 on 2025-04-28 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alert_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dismissed_by',
            field=models.ManyToManyField(blank=True, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
