# Generated by Django 5.1.5 on 2025-04-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alert_dismissed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_government',
            field=models.BooleanField(default=False),
        ),
    ]
