# Generated by Django 5.1.5 on 2025-04-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alert_is_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='noaa_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
